### ISSUE TITLE
Manuals are not being updated after editing a step

### ISSUE THREAD

**Issue by DAB0mB** [Urigo/tortilla#14]
Manuals are not being updated after editing a step.

To solve it we need to convert the manuals manually after we've edited the step, while it can all be done as part of the editing mode

**Comment by darkbasic** [comment]
This is a killer feature in my opinion. I don't necessarily need tortilla to render the manuals after editing a step, but at least I expect it to reword diffsteps numbers in the template. Let's say I pop or push a step in the middle of a chapter: tortilla should automatically reword all subsequent diffsteps in the template so that they point to the right diffstep.

```
{{{diffStep "4.6"}}}
{{{diffStep "4.8"}}}
{{{diffStep "4.9"}}}
{{{diffStep "4.11"}}}
```

`tortilla step pop 4.8`

becomes:

```
{{{diffStep "4.6"}}}
{{{diffStep "4.8"}}}
{{{diffStep "4.10"}}}
```
